### ISSUE TITLE
Need some tweaks for 10k Apart

### ISSUE THREAD

**Issue by aarongustafson** [sapegin/sapegin.me#1]
We either need the root of master to contain your project (which is currently in `./public`) or we need you to add a web.config file to instruct IIS to use `./public/` as the root folder.

**Comment by sapegin** [comment]
Thanks! I’ll create a separate repository for the contest since it’s just the source code but you need compiled HTML files.

**Comment by aarongustafson** [comment]
Sounds good. I will reject the original entry so you can re-submit it.
